---
- name: Setup some facts
  set_fact:
    intellij_community_src_directory:
      /usr/local/src/intellij-community

- name: Checkout from github
  git:
    repo: https://github.com/JetBrains/intellij-community.git
    dest: "{{ intellij_community_src_directory }}"
    version: master
    depth: 1
    update: false

- name: Determine if file-watcher has already been compiled
  stat:
    path:
      "{{ intellij_community_src_directory }}/native/fsNotifier/\
      linux/fsnotifier-{{ ansible_architecture }}"
    checksum_algorithm: sha256
  register: compiled_file_watcher

- name: Compile file-watcher for aarch
  command: './make.sh'
  args:
    chdir:
      "{{ intellij_community_src_directory }}/\
      native/fsNotifier/linux"
  when: not compiled_file_watcher.stat.exists

- name: Determine if file-watcher has already been copied
  stat:
    path: /usr/local/bin/fsnotifier
    checksum_algorithm: sha256
  register: copied_file_watcher

- name: Estimate if file-watcher needs to be copied
  set_fact:
    copy_file_watcher: "{{
      not copied_file_watcher.stat.exists
      or compiled_file_watcher.stat.checksum
        != copied_file_watcher.stat.checksum
      }}"

- name: Copy compiled file-watcher to CLion
  copy:
    src:
      "{{ intellij_community_src_directory }}/\
      native/fsNotifier/linux/fsnotifier-{{ ansible_architecture }}"
    dest: /usr/local/bin/fsnotifier
    remote_src: true
    mode: 0755
  when: copy_file_watcher

- name: Setup file-watcher usage
  lineinfile:
    path: "{{ clion_installation_dir }}/bin/idea.properties"
    regexp: '^idea.filewatcher.executable.path'
    line:
      "idea.filewatcher.executable.path = /usr/local/bin/fsnotifier"
