---
- name: Checkout from github
  git:
    repo: https://github.com/JetBrains/pty4j.git
    dest: /opt/github/JetBrains/pty4j
    version: 1ae19e6  # Version 0.9.6

- name: Create Makefile for aarch
  template:
    src: templates/pty4j-aarch/Makefile
    dest: /opt/github/JetBrains/pty4j/native/Makefile_aarch
    owner: root
    group: root
    mode: 0755
  register: docker_add_user_script

- name: Setup target path for aarch64
  set_fact:
    libpty_destination:
      "{{ clion_installation_dir }}/lib/pty4j-native/linux/x86_64/libpty.so"
  when: ansible_architecture == 'aarch64'

- name: Setup target path for armv7l
  set_fact:
    libpty_destination:
      "{{ clion_installation_dir }}/lib/pty4j-native/linux/x86/libpty.so"
  when: ansible_architecture == 'armv7l'

- name: Setup compiled lib path
  set_fact:
    compiled_libpty:
      "/opt/github/JetBrains/pty4j/os/linux/\
      {{ ansible_architecture }}/libpty.so"

- name: Determine if pty4j has already been compiled
  stat:
    path: "{{ compiled_libpty }}"
    checksum_algorithm: sha256
  register: compiled_pty4j

- name: Compile pty4j for aarch
  command: 'make --makefile=Makefile_aarch'
  args:
    chdir: /opt/github/JetBrains/pty4j/native
  when: not compiled_pty4j.stat.exists
  register: pty4j_compiled

- name: Check pty4j destination file
  stat:
    path: "{{ libpty_destination }}"
    checksum_algorithm: sha256
  register: pty4j_destination

- name: Estimate if pty4j needs to be copied
  set_fact:
    copy_pty4j: "{{
      pty4j_compiled.changed
      or compiled_pty4j.stat.checksum != pty4j_destination.stat.checksum
      }}"

- name: Replace pty4j module
  copy:
    src: "{{ compiled_libpty }}"
    dest: "{{ libpty_destination }}"
    remote_src: true
    mode: 0755
  when: copy_pty4j | bool
